apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dotnet60-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dotnet60-sample
    app.kubernetes.io/part-of: test-dot-net-application
  name: dotnet60-sample
  namespace: johnmcollier
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: dotnet60-sample
    weight: 100
status: {}
